[package]
name = "alfis"
version = "0.3.0"
authors = ["Revertron <alfis@revertron.com>"]
edition = "2018"
build = "build.rs"
readme = "README.md"
homepage = "https://alfis.name"
repository = "https://github.com/Revertron/Alfis"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
log = "0.4.14"
simple_logger = "1.11.0"
toml = "0.5.8"
rust-crypto = "^0.2"
blakeout = "0.1.0"
num_cpus = "1.13.0"
byteorder = "1.3.2"
web-view = { version = "0.7.2", features = [] }
tinyfiledialogs = "3.3.10"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.42"
num-bigint = "0.4"
num-traits = "0.2"
bincode = "1.2.0"
base64 = "0.13.0"
chrono = { version = "0.4.13", features = ["serde"] }
rand = "0.8.3"
sqlite = "0.25.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
mio = { version = "0.7", features = ["os-poll", "net"] }
# for DNS from hermes
derive_more = "0.99.9"

[target.'cfg(windows)'.dependencies]
thread-priority = "0.2.1"
winapi = { version = "0.3.7", features = ["impl-default", "wincon"]}

[target.'cfg(target_os = "linux")'.dependencies]
thread-priority = "0.2.1"

[build-dependencies]
minreq = { version = "2.3.1", features = ["punycode", "https-rustls"] }
rust-crypto = "^0.2"
winres = "0.1"

[dev-dependencies]
serde_bytes = "0.11.2"
serde_derive = "1.0.27"

[profile.dev]
opt-level = 2

[profile.test]
opt-level = 2

[package.metadata.winres]
ProductName="ALFIS"
FileDescription="Alternative Free Identity System"