[package]
name = "alfis"
version = "0.1.0"
authors = ["Revertron <rev@revertron.com>"]
edition = "2018"
build = "build.rs"
#![windows_subsystem = "windows"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
num_cpus = "1.13.0"
byteorder = "1.3.2"
web-view = { version = "0.7.2", features = [] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.42"
num-bigint = "0.2"
num-traits = "0.2"
bincode = "1.2.0"
groestl = "0.8.0"
base64 = "0.11.0"
chrono = "0.4.9"
rand = "0.7.2"
sqlite = "0.25.3"
eventbus = "0.5.1"

[build-dependencies]
winres = "0.1"

[dev-dependencies]
serde_bytes = "0.11.2"
serde_derive = "1.0.27"

[package.metadata.winres]
ProductName="ALFIS"
FileDescription="Alternative Free Identity System for independent DNS and more."