[package]
name = "alfis"
version = "0.1.0"
authors = ["Revertron <alfis@revertron.com>"]
edition = "2018"
build = "build.rs"
readme = "README.md"
homepage = "https://alfis.name"
repository = "https://github.com/Revertron/Alfis"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2.21"
rust-crypto = "^0.2"
num_cpus = "1.13.0"
byteorder = "1.3.2"
web-view = { version = "0.7.2", features = [] }
tinyfiledialogs = "3.3.10"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.42"
num-bigint = "0.2"
num-traits = "0.2"
bincode = "1.2.0"
groestl = "0.8.0"
base64 = "0.11.0"
chrono = { version = "0.4.13", features = ["serde"] }
rand = "0.7.2"
sqlite = "0.25.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
mio = { version = "0.7", features = ["os-poll", "net"] }
# for DNS from hermes
derive_more = "0.99.9"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["impl-default", "wincon"]}

[build-dependencies]
winres = "0.1"

[dev-dependencies]
serde_bytes = "0.11.2"
serde_derive = "1.0.27"

[package.metadata.winres]
ProductName="ALFIS"
FileDescription="Alternative Free Identity System"