brace_style = "PreferSameLine"
comment_width = 140
fn_args_layout = "Compressed"
group_imports = "StdExternalCrate"
imports_granularity = "Module"
max_width = 140
newline_style = "Unix"
reorder_impl_items = true
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
where_single_line = true